global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    dns_sd_configs:
      - names: ['api-gateway']
        type: 'A'
        port: 3000

  - job_name: 'orchestrator'
    dns_sd_configs:
      - names: ['orchestrator']
        type: 'A'
        port: 8080

  - job_name: 'worker-node'
    dns_sd_configs:
      - names: ['worker-node']
        type: 'A'
        port: 5000

  - job_name: 'database-webhook-node'
    static_configs:
      - targets: ['database-webhook-node:4000']
