{
 "title": "Booking System Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Processed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_processed_jobs_total)"
    }
   ]
  },
  {
   "title": "Successful Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_successful_jobs_total)"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(worker_failed_jobs_total)" }
   ]
  },
  {
   "title": "Go Goroutines (Orchestrator)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(go_goroutines) by (instance)",
     "legendFormat": "{{job}} Goroutines"
    }
   ]
  },
  {
   "title": "Node.js Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(nodejs_heap_space_size_used_bytes) by (instance, space)",
     "legendFormat": "{{job}} - {{space}}"
    }
   ]
  }
 ]
}